language: java
jdk:
    - oraclejdk8
after_success:
- python <(curl -s https://raw.githubusercontent.com/lordOfSputnik/sputnik-test/sputnikRulesViolated/sputnik-ci.py)

env:
  global:
  - secure: KbOA1GsIRhPDsaoYUv4AjB2SS7RZfDuqrZuQxSVtkQn6Y4vQ3PtCSlcT/Bmup3214D3EdML0aR9i/B3YlS9YYLXiqrvWQ/zIfTdQR4sNUfVjU4ZxgPk1+/FRSF22DloQXgslrrBn0F6KQlmU1O0YKInEdMzJmYv22v+GPEFihg/4/HYvI086dJD+h6VZbDz07Imea2JrwGew6OcgBcipP2s9hraURJS/SAZ7nqeQ82Nze4xjo5CKs8JhrsnBxFBLbqqPcK3QWkFyCk4NozaPYInJRV2AQ9ArWenvm3Ogh0AbwcHmqCzGfhyIshXN3cgIusAuKKXoCNjiy9Riwsno7AGKqCToU1siuqPSXPgVDdhx1FzUPuNJ8y1SbeEpvb66gtltIKRo6djBmEYPP/RRUhRIK+Ae+ZjsK9iIsIExlBsQIduw0XFYxCk0CgQT1LtAF7hCje7CMDhxOHc6Ae4ppqFWjzl9A8iFlkApqeuxSy+Mx4aVAHTZq1PeIMZvkHTyP8fBVp0RGoHHecrzPATwJlj9ZDCM+h2WwtEPBbclw2tNxtjzv/bIhAxg0qVbTl5uh25gUNMhgfEAuLwWGcc+L5Awg5x1w2CYud8NyXfpqsPZ67B5yNfrY8Ou4KFYJhHyiv6WGJmO0gQ9WMBZFjsKxyFk6KfsMhecRdpdZBZ2Xxw=